Backend
dzharlaksl/urfu_pi2_1_7 pull request #6
Opened 2024-03-25 15:33 UTC by synrocka

Добавлен API.

2024-03-26 22:51 UTC, operevispa requested changes
Привет. Комментарии оставил в тексте кода. Пожалуйста, посмотри актуальную версию файла categorize и обрати внимание на структуру словаря, возвращаемого твоими api-методом. Спасибо.

2024-03-26 22:51 UTC, operevispa commented on src/main.py
> +@app.post("/model/")
Поменяй, пожалуйста роут на get_ticket_api вмеcто model. Название метода API "model" не очень понятно, что делает и желательно дать более говорящее название методу. 
get_ticket_api я также попросил использовать @bev141 для вызова твоего API

2024-03-26 22:51 UTC, operevispa commented on src/main.py
> +    categorization = categorize.process_texts(transcription)
последняя версия файла categorize сегодня смерджена в ветку develop.
Пожалуйста, посмотри название функции и возвращаемые параметры.
По договоренности с другими членами команды, твой метод должен возвращать словарь с тремя парами ключ-значение: ticket_text (str), category (int), priority (int)

2024-03-27 06:10 UTC, bev141 commented on src/main.py
> +@app.post("/model/")
По-моему POST запрос на метод get_ticket_api тоже странно смотрится. Может /ticket-info/ или /api/ticket-info/ ? Так более логично по-моему.

2024-03-27 08:39 UTC, bev141 approved these changes
Все хорошо. Локально потестил, работает.

2024-03-27 08:47 UTC, operevispa approved these changes
Согласен,  get_ticket_api для метода POST звучит как издевательство над здравым 
смыслом )))
Спасибо за правки. Отлично.

2024-03-27 08:48 UTC, merged